apiVersion: v1
kind: Pod
metadata:
    name: microservice-libreria-pod
    labels:
        app: microservice-libreria
        type: microservice
spec:
    container:
    - name: microservice-libreria-app
      image: jeffgar49/serviciosapilibreria:latest
      ports: 
        - containerPort: 80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://jeffgar:$jeff123@mongo-service:27017
          