apiVersion: v1
kind: Pod
metadata:
    name: mongo-pod
    labels:
        app: microservice-libreria
        name: mongo-pod
spec:
    container:
    - name: mongo
      image: mongo:latest
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "jeffgar"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "$jeff123"
      ports: 
        - containerPort: 27017