apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-deploy
    labals:
        name: mssql-deploy
        app: microservice-seguridad
spec:
    replicas: 1
    selector:
        matchLabels:
            app: microservice-seguridad
            name: mssql-pod
    template:
        metadata:
            name: sqlserver-pod
            labels:
                app: microservice-seguridad
                name: mssql-pod
        spec:
            container:
                - name: mssql
                  image: mcr.microsoft.com/mssql/server:latest
                  ports: 
                    - containerPort: 1433
                  env:
                    - name: ACCEPT_EULA
                      value: "Y"
                    - name: SA_PASSWORD
                      value: "$jeff123"