apiVersion: v1
kind: Pod
metadata:
    name: sqlserver-pod
    labels:
        app: microservice-seguridad
        name: mssql-pod
spec:
    container:
    - name: mssql
      image: mcr.microsoft.com/mssql/server:latest
      ports: 
        - containerPort: 1433
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "$jeff123"